class bugsfixed.varusage:
  define private static variable x1 as char.
  define private variable x2 as char.
  define private variable x3 as char.
  define private variable x4 as char.

  define variable lProcedure1 as handle no-undo.
  define variable lProcedure2 as handle no-undo.
  define variable lApsv as handle no-undo.
  define variable lRun  as handle no-undo.

  constructor varusage(prm as char):
    this-object:mthd2(bugsfixed.varusage:x1, x2).
  end.

end.
